tasmota_devicelist:
  - friendly-name: test #this is a device with only one relay so there is no need to assign id
    ip: 192.168.88.233 
  - friendly-name: tv box
    id: POWER1 #this is a device with multiple relays so each relay should have the same ip and an id (Power1,Power2 ...etc)
    ip: 192.168.88.234
  - friendly-name: tv 
    id: POWER2
    ip: 192.168.88.234
gmusicapi:
  #If you are using two-step authentication, use app specific password. For guidelines, go through README
  email : mohammad.rasim96@gmail.com
  password : upfsdqorvxrenulo

#API Key for YouTube and Kickstarter Search Engine
google_cloud_api_key: ENTER-YOUR-GOOGLE-CLOUD-API-KEY-HERE

kodi:
  ip: 192.168.88.226
  port: 8080
  username: kodi
  password: kodi
  musicdirectory: /home/osmc/Music/
  videodirectory: /home/osmc/Movies/
  windowcmd: 
    - Home
    - Settings
    - Weather
    - Videos
    - Music
    - Player
  window: 
    - home
    - settings
    - weather
    - videos
    - music
    - playercontrols
Radio_stations:
    - name: 'bbc 2'
      url: 'http://www.radiofeeds.co.uk/bbcradio2.pls'

    - name: 'bbc 6 music'
      url: 'http://www.radiofeeds.co.uk/bbc6music.pls'

    - name: 'Radio 3'
      url: 'http://c5icy.prod.playlists.ihrhls.com/1469_icy'

    - name: 'Radio 4'
      url: 'http://playerservices.streamtheworld.com/api/livestream-redirect/ARNCITY.mp3'
    #Ascii value of the trigger key, to get the Ascii value of any key run the getkeystroke.py
    # and press the key you want and then change triggerkey
trigger_key: 201
  
...
